version: "3.7"

networks:
  proxy:
    name: ${NETWORK_NAME}
    external: true

services:
  # This container will do NOTHING but the reverse proxy (and cert management).
  caddy:
    container_name: proxy
    image: homeall/caddy-reverse-proxy-cloudflare:latest
    environment:
      TZ: 'America/Los_Angeles'
      CADDY_INGRESS_NETWORKS: ${NETWORK_NAME}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" #### needed socket to read events
      - "./certs:/data" #### needed volume to back up certificates
    labels:
      caddy.email: ${EMAIL}
    networks:
      - proxy
    restart: unless-stopped
#    depends_on:
#      - hupi
#      - wiki
    